### ISSUE TITLE
I would add more colour to your profile and some other tips :)

### ISSUE THREAD

**Issue by elenajp** [tansionline/tansionline#2]
Hey Selçuk! 

I have recently made a start on my GitHub profile and I think it looks better with some colour! Have a look:

[](https://github.com/elenajp)

I am still working on it though. I think your profile would be great with some more colour on it too. 
I made some changes below, I hope you like them:

🎉 Hey, I'm a student developer from Antalya/Turkey.
🧐 Interests: Open-source, security, development, cats, walking, meeting new people. 😻
📝 Skills: I use JavaScript, Node.js, VueJS, React. And I know how to google. 😅
📙 You can reach me here.

I would suggest replacing that gif about nameless to a cool banner photo too.

I see you are smashing the green squares, well done!

**Comment by tansionline** [comment]
Thank you for your contribution. I will add some icons like [this](https://github.com/mby/mby) profile. I hope this makes it more colourful.

**Comment by elenajp** [comment]
It will look great, I am sure! Have fun doing it 😀
